<?xml version="1.0" encoding="utf-8"?><Database Name="IssueTracker" Class="IssueTrackerDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=IssueTracker;Integrated Security=True" SettingsObjectName="IssueTracker.Data.Properties.Settings" SettingsPropertyName="IssueTrackerConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Issue" Member="Issues">
    <Type Name="Issue">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProjectId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AssignedUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OpenedByUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MilestoneId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsOpen" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreationDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastUpdatedDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Body" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="Issue_IssueLabel" Member="IssueLabels" ThisKey="Id" OtherKey="IssueId" Type="IssueLabel" />
      <Association Name="User_Issue" Member="OpenedByUser" Storage="_User" ThisKey="OpenedByUserId" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="User_Issue1" Member="AssignedUser" Storage="_User1" ThisKey="AssignedUserId" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="Milestone_Issue" Member="Milestone" ThisKey="MilestoneId" OtherKey="Id" Type="Milestone" IsForeignKey="true" />
      <Association Name="Project_Issue" Member="Project" ThisKey="ProjectId" OtherKey="Id" Type="Project" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Association Name="User_Issue" Member="OpenedIssues" Storage="_Issues" ThisKey="Id" OtherKey="OpenedByUserId" Type="Issue" />
      <Association Name="User_Issue1" Member="AssignedIssues" Storage="_Issues1" ThisKey="Id" OtherKey="AssignedUserId" Type="Issue" />
      <Association Name="User_ProjectUser" Member="ProjectUsers" ThisKey="Id" OtherKey="UserId" Type="ProjectUser" />
    </Type>
  </Table>
  <Table Name="dbo.IssueLabel" Member="IssueLabels">
    <Type Name="IssueLabel">
      <Column Name="IssueId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LabelId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Issue_IssueLabel" Member="Issue" ThisKey="IssueId" OtherKey="Id" Type="Issue" IsForeignKey="true" />
      <Association Name="Label_IssueLabel" Member="Label" ThisKey="LabelId" OtherKey="Id" Type="Label" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Label" Member="Labels">
    <Type Name="Label">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="ColorValue" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Label_IssueLabel" Member="IssueLabels" ThisKey="Id" OtherKey="LabelId" Type="IssueLabel" />
    </Type>
  </Table>
  <Table Name="dbo.Milestone" Member="Milestones">
    <Type Name="Milestone">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProjectId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DueDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="Milestone_Issue" Member="Issues" ThisKey="Id" OtherKey="MilestoneId" Type="Issue" />
      <Association Name="Project_Milestone" Member="Project" ThisKey="ProjectId" OtherKey="Id" Type="Project" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Project" Member="Projects">
    <Type Name="Project">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CreationDateTIme" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="Project_Issue" Member="Issues" ThisKey="Id" OtherKey="ProjectId" Type="Issue" />
      <Association Name="Project_Milestone" Member="Milestones" ThisKey="Id" OtherKey="ProjectId" Type="Milestone" />
      <Association Name="Project_ProjectUser" Member="ProjectUsers" ThisKey="Id" OtherKey="ProjectId" Type="ProjectUser" />
    </Type>
  </Table>
  <Table Name="dbo.ProjectUser" Member="ProjectUsers">
    <Type Name="ProjectUser">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProjectId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Project_ProjectUser" Member="Project" ThisKey="ProjectId" OtherKey="Id" Type="Project" IsForeignKey="true" />
      <Association Name="User_ProjectUser" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
</Database>